### ISSUE TITLE
Add the warning if fasm was not found

### ISSUE THREAD

**Issue by farkon00** [farkon00/cont#11]
How about checking if fasm is installed when the cont starts and throw an error with an instrctruction to install it using `apt` if it was not found.

**Comment by juniorfr** [comment]
Add in test.py:
`os.system('fasm -v')`
Adding conditionals to the answer, I think it's a good idea

**Comment by juniorfr** [comment]
Using this command:
`subprocess.getstatusoutput('fasm -v')`
It return in first position a binary

**Comment by farkon00** [comment]
> Using this command: `subprocess.getstatusoutput('fasm -v')` It return in first position a binary

Yes, seems like a good idea

**Comment by juniorfr** [comment]
For me, this is easier than parsing the return string from `os.system('fasm -v')`

**Comment by farkon00** [comment]
Resolved in #12
