### ISSUE TITLE
feat trequest: type aliases

### ISSUE THREAD

**Issue by lambdasapple** [farkon00/cont#50]
C style type aliases would be really helpful. :heart: 

I look forward to hearing from you;
please let me know if you have any questions

**Comment by farkon00** [comment]
For history preservation purposes:
![image](https://github.com/user-attachments/assets/48d4e858-9280-4846-a8f1-4cf67c5e0393)

**Comment by lambdasapple** [comment]
> For history preservation reasons: ![image](https://private-user-images.githubusercontent.com/59134591/373378364-48d4e858-9280-4846-a8f1-4cf67c5e0393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODE5MjQsIm5iZiI6MTcyNzk4MTYyNCwicGF0aCI6Ii81OTEzNDU5MS8zNzMzNzgzNjQtNDhkNGU4NTgtOTI4MC00ODQ2LWE4ZjEtNGNmNjdjNWUwMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE4NTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTM1ZmMyYmE3NDlkNzg5MmM5OWY3YjA0Zjk3MTQzZmQ0OTY0Yzg4Mzg5MDIxOWI0YjZkZDk0ODcxOTk5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q7F2Rt85y95QQsCLDaGWScpSZcyMzO1Lk07-ljgV-oI)

I call photoshop. Specifically GIMP

**Comment by farkon00** [comment]
> > For history preservation reasons: ![image](https://private-user-images.githubusercontent.com/59134591/373378364-48d4e858-9280-4846-a8f1-4cf67c5e0393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODE5MjQsIm5iZiI6MTcyNzk4MTYyNCwicGF0aCI6Ii81OTEzNDU5MS8zNzMzNzgzNjQtNDhkNGU4NTgtOTI4MC00ODQ2LWE4ZjEtNGNmNjdjNWUwMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE4NTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTM1ZmMyYmE3NDlkNzg5MmM5OWY3YjA0Zjk3MTQzZmQ0OTY0Yzg4Mzg5MDIxOWI0YjZkZDk0ODcxOTk5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q7F2Rt85y95QQsCLDaGWScpSZcyMzO1Lk07-ljgV-oI)
> 
> I call photoshop. Specifically GIMP

GIMP is barely usable and I do not have it installed, I use Krita. Also it would be much easier to fake it with dev tools.
